const awardData = {
    orangeCap: [
        { year: 2008, player: "Shaun Marsh", team: "KXIP", runs: 616 },
        { year: 2009, player: "Matthew Hayden", team: "CSK", runs: 572 },
        { year: 2010, player: "Sachin Tendulkar", team: "MI", runs: 618 },
        { year: 2011, player: "Chris Gayle", team: "RCB", runs: 608 },
        { year: 2012, player: "Chris Gayle", team: "RCB", runs: 733 },
        { year: 2013, player: "Michael Hussey", team: "CSK", runs: 733 },
        { year: 2014, player: "Robin Uthappa", team: "KKR", runs: 660 },
        { year: 2015, player: "David Warner", team: "SRH", runs: 562 },
        { year: 2016, player: "Virat Kohli", team: "RCB", runs: 973 },
        { year: 2017, player: "David Warner", team: "SRH", runs: 641 },
        { year: 2018, player: "Kane Williamson", team: "SRH", runs: 735 },
        { year: 2019, player: "David Warner", team: "SRH", runs: 692 },
        { year: 2020, player: "KL Rahul", team: "PBKS", runs: 670 },
        { year: 2021, player: "Ruturaj Gaikwad", team: "CSK", runs: 635 },
        { year: 2022, player: "Jos Buttler", team: "RR", runs: 863 },
        { year: 2023, player: "Shubman Gill", team: "GT", runs: 890 },
        { year: 2024, player: "Virat Kohli", team: "RCB", runs: 741 },
        { year: 2025, player: "Sai Sudharsan", team: "GT", runs: 759 },
    ],

    purpleCap: [
        { year: 2008, player: "Sohail Tanvir", team: "RR", wickets: 22 },
        { year: 2009, player: "RP Singh", team: "DC", wickets: 23 },
        { year: 2010, player: "Pragyan Ojha", team: "DC", wickets: 21 },
        { year: 2011, player: "Lasith Malinga", team: "MI", wickets: 28 },
        { year: 2012, player: "Morne Morkel", team: "DD", wickets: 25 },
        { year: 2013, player: "Dwayne Bravo", team: "CSK", wickets: 32 },
        { year: 2014, player: "Mohit Sharma", team: "CSK", wickets: 23 },
        { year: 2015, player: "Dwayne Bravo", team: "CSK", wickets: 26 },
        { year: 2016, player: "Bhuvneshwar Kumar", team: "SRH", wickets: 23 },
        { year: 2017, player: "Bhuvneshwar Kumar", team: "SRH", wickets: 26 },
        { year: 2018, player: "Andrew Tye", team: "PBKS", wickets: 24 },
        { year: 2019, player: "Imran Tahir", team: "CSK", wickets: 26 },
        { year: 2020, player: "Kagiso Rabada", team: "DC", wickets: 30 },
        { year: 2021, player: "Harshal Patel", team: "RCB", wickets: 32 },
        { year: 2022, player: "Yuzvendra Chahal", team: "RR", wickets: 27 },
        { year: 2023, player: "Mohammed Shami", team: "GT", wickets: 28 },
        { year: 2024, player: "Harshal Patel", team: "PBKS", wickets: 24 },
        { year: 2025, player: "Prasidh Krishna", team: "GT", wickets: 25 },
    ],

    winners: [
        { year: 2008, team: "RAJASTHAN ROYALS", logo: "Logo/rr.png" },
        { year: 2009, team: "DECCAN CHARGERS", logo: "Logo/dec.png" },
        { year: 2010, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" },
        { year: 2011, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" },
        { year: 2012, team: "KOLKATA KNIGHT RIDERS", logo: "Logo/kkr.png" },
        { year: 2013, team: "MuUMBAI INDIANS", logo: "Logo/mi.png" },
        { year: 2014, team: "KOLKATA KNIGHT RIDERS", logo: "Logo/kkr.png" },
        { year: 2015, team: "MuUMBAI INDIANS", logo: "Logo/mi.png" },
        { year: 2016, team: "SUNRISERS HYDERABAD", logo: "Logo/srh.png" },
        { year: 2017, team: "MuUMBAI INDIANS", logo: "Logo/mi.png" },
        { year: 2018, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" },
        { year: 2019, team: "MuUMBAI INDIANS", logo: "Logo/mi.png" },
        { year: 2020, team: "MuUMBAI INDIANS", logo: "Logo/mi.png" },
        { year: 2021, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" },
        { year: 2022, team: "GUJARAT TITANS", logo: "Logo/gt.png" },
        { year: 2023, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" },
        { year: 2024, team: "KOLKATA KNIGHT RIDERS", logo: "Logo/kkr.png" },
        { year: 2025, team: "ROYAL CHALLENGERS BENGALURU", logo: "Logo/rcb.png" },
    ],

    fairplayAward: [
        { year: 2008, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" },
        { year: 2009, team: "KINGS XI PUNJAB", logo: "Logo/kxip.png" },
        { year: 2010, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" },
        { year: 2011, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" },
        { year: 2012, team: "RAJASTHAN ROYALS", logo: "Logo/rr.png" },
        { year: 2013, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" },
        { year: 2014, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" },
        { year: 2015, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" },
        { year: 2016, team: "SUNRISERS HYDERABAD", logo: "Logo/srh.png" },
        { year: 2017, team: "GUJARAT LIONS", logo: "Logo/gl.png" },
        { year: 2018, team: "MuUMBAI INDIANS", logo: "Logo/mi.png" },
        { year: 2019, team: "SUNRISERS HYDERABAD", logo: "Logo/srh.png" },
        { year: 2020, team: "MuUMBAI INDIANS", logo: "Logo/mi.png" },
        { year: 2021, team: "RAJASTHAN ROYALS", logo: "Logo/rr.png" },
        { year: 2022, team: "GUJARAT TITANS", logo: "Logo/gt.png" },
        { year: 2023, team: "DELHI CAPITALS", logo: "Logo/dc.png" },
        { year: 2024, team: "SUNRISERS HYDERABAD", logo: "Logo/srh.png" },
        { year: 2025, team: "CHENNAI SUPER KINGS", logo: "Logo/csk.png" }
    ],
    emergingPlayer: [
        { year: 2008, player: "Shreevats Goswami", team: "RCB" },
        { year: 2009, player: "Rohit Sharma", team: "DEC" },
        { year: 2010, player: "Saurabh Tiwary", team: "MI" },
        { year: 2011, player: "Iqbal Abdulla", team: "KKR" },
        { year: 2012, player: "Mandeep Singh", team: "KXIP" },
        { year: 2013, player: "Sanju Samson", team: "RR" },
        { year: 2014, player: "Axar Patel", team: "KXIP" },
        { year: 2015, player: "Shreyas Iyer", team: "DD" },
        { year: 2016, player: "Mustafizur Rahman", team: "SRH" },
        { year: 2017, player: "Basil Thampi", team: "GL" },
        { year: 2018, player: "Rishabh Pant", team: "DD" },
        { year: 2019, player: "Shubman Gill", team: "KKR" },
        { year: 2020, player: "Devdutt Padikkal", team: "RCB" },
        { year: 2021, player: "Ruturaj Gaikwad", team: "CSK" },
        { year: 2022, player: "Umran Malik", team: "SRH" },
        { year: 2023, player: "Yashasvi Jaiswal", team: "RR" },
        { year: 2024, player: "Nitish Kumar Reddy", team: "SRH" },
        { year: 2025, player: "Sai Sudharsan", team: "GT" }
    ],
    mvp: [
        { year: 2008, player: "Shane Watson", team: "RR" },
        { year: 2009, player: "Adam Gilchrist", team: "DEC" },
        { year: 2010, player: "Sachin Tendulkar", team: "MI" },
        { year: 2011, player: "Chris Gayle", team: "RCB" },
        { year: 2012, player: "Sunil Narine", team: "KKR" },
        { year: 2013, player: "Shane Watson", team: "RR" },
        { year: 2014, player: "Glenn Maxwell", team: "KXIP" },
        { year: 2015, player: "Andre Russell", team: "KKR" },
        { year: 2016, player: "Virat Kohli", team: "RCB" },
        { year: 2017, player: "Ben Stokes", team: "RPS" },
        { year: 2018, player: "Sunil Narine", team: "KKR" },
        { year: 2019, player: "Andre Russell", team: "KKR" },
        { year: 2020, player: "Jofra Archer", team: "RR" },
        { year: 2021, player: "Harshal Patel", team: "RCB" },
        { year: 2022, player: "Jos Buttler", team: "RR" },
        { year: 2023, player: "Shubman Gill", team: "GT" },
        { year: 2024, player: "Sunil Narine", team: "KKR" },
        { year: 2025, player: "Suryakumar Yadav", team: "MI" }
    ],
    mostSixes: [
        { year: 2008, player: "Sanath Jayasuriya", team: "MI", sixes: 31 },
        { year: 2009, player: "Adam Gilchrist", team: "DEC", sixes: 29 },
        { year: 2010, player: "Robin Uthappa", team: "RCB", sixes: 27 },
        { year: 2011, player: "Chris Gayle", team: "RCB", sixes: 44 },
        { year: 2012, player: "Chris Gayle", team: "RCB", sixes: 59 },
        { year: 2013, player: "Chris Gayle", team: "RCB", sixes: 51 },
        { year: 2014, player: "Glenn Maxwell", team: "KXIP", sixes: 36 },
        { year: 2015, player: "Chris Gayle", team: "RCB", sixes: 38 },
        { year: 2016, player: "Virat Kohli", team: "RCB", sixes: 38 },
        { year: 2017, player: "Glenn Maxwell", team: "KXIP", sixes: 26 },
        { year: 2018, player: "Rishabh Pant", team: "DD", sixes: 37 },
        { year: 2019, player: "Andre Russell", team: "KKR", sixes: 52 },
        { year: 2020, player: "Ishan Kishan", team: "MI", sixes: 30 },
        { year: 2021, player: "KL Rahul", team: "PBKS", sixes: 30 },
        { year: 2022, player: "Jos Buttler", team: "RR", sixes: 45 },
        { year: 2023, player: "Faf du Plessis", team: "RCB", sixes: 36 },
        { year: 2024, player: "Abhishek Sharma", team: "SRH", sixes: 42 },
        { year: 2025, player: "Nicholas Pooran", team: "LSG", sixes: 40 }
    ],
    PlayeroftheFinal: [
        { year: 2008, player: "Yusuf Pathan", team: "RR" },
        { year: 2009, player: "Anil Kumble", team: "RCB" },
        { year: 2010, player: "Suresh Raina", team: "CSK" },
        { year: 2011, player: "Murali Vijay", team: "CSK" },
        { year: 2012, player: "Manvinder Bisla", team: "KKR" },
        { year: 2013, player: "Kieron Pollard", team: "MI" },
        { year: 2014, player: "Manish Pandey", team: "KKR" },
        { year: 2015, player: "Rohit Sharma", team: "MI" },
        { year: 2016, player: "Ben Cutting", team: "SRH" },
        { year: 2017, player: "Krunal Pandya", team: "MI" },
        { year: 2018, player: "Shane Watson", team: "CSK" },
        { year: 2019, player: "Jasprit Bumrah", team: "MI" },
        { year: 2020, player: "Trent Boult", team: "MI" },
        { year: 2021, player: "Faf du Plessis", team: "CSK" },
        { year: 2022, player: "Hardik Pandya", team: "GT" },
        { year: 2023, player: "Devon Conway", team: "CSK" },
        { year: 2024, player: "Mitchell Starc", team: "KKR" },
        { year: 2025, player: "Krunal Pandya", team: "RCB" }
    ]
};
