const teams = {
  csk: {
    name: "Chennai Super Kings",
    logo: "Logo/csk.png",
    captain: "Ruturaj Gaikwad",
    coach: "Stephen Fleming",
    home: "M. A. Chidambaram Stadium, Chennai",
    titles: 5,
    titleYears: "2010, 2011, 2018, 2021, 2023",
  },
  mi: {
    name: "Mumbai Indians",
    logo: "Logo/mi.png",
    captain: "Hardik Pandya",
    coach: "Mahela Jayawardene",
    home: "Wankhede Stadium, Mumbai",
    titles: 5,
    titleYears: "2013, 2015, 2017, 2019, 2020",
  },
  rcb: {
    name: "Royal Challengers Bengaluru",
    logo: "Logo/rcb.png",
    captain: "Rajat Patidar",
    coach: "Andy Flower",
    home: "M. Chinnaswamy Stadium, Bengaluru",
    titles: 1,
    titleYears: "2025",
  },
  kkr: {
    name: "Kolkata Knight Riders",
    logo: "Logo/kkr.png",
    captain: "Ajinkya Rahane",
    coach: "Chandrakant Pandit",
    home: "Eden Gardens, Kolkata",
    titles: 3,
    titleYears: "2012, 2014, 2024",
  },
  rr: {
    name: "Rajasthan Royals",
    logo: "Logo/rr.png",
    captain: "Sanju Samson",
    coach: "Rahul Dravid",
    home: "Sawai Mansingh Stadium, Jaipur",
    titles: 1,
    titleYears: "2008",
  },
  srh: {
    name: "Sunrisers Hyderabad",
    logo: "Logo/srh.png",
    captain: "Pat Cummins",
    coach: "Daniel Vettori",
    home: "Rajiv Gandhi International Cricket Stadium, Hyderabad",
    titles: 1,
    titleYears: "2016",
  },
  dc: {
    name: "Delhi Capitals",
    logo: "Logo/dc.png",
    captain: "Axar Patel",
    coach: "Hemang Badani",
    home: "Arun Jaitley Stadium, New Delhi",
    titles: 0,
    titleYears: "Yet to Win",
  },
  pbks: {
    name: "Punjab Kings",
    captain: "Shreyas Iyer",
    logo: "Logo/pbks.png",
    coach: "Ricky Pionting",
    home: "New PCA Stadium, Mullanpur",
    titles: 0,
    titleYears: "Yet to Win",
  },
  gt: {
    name: "Gujarat Titans",
    logo: "Logo/gt.png",
    captain: "Shubman Gill",
    coach: "Ashish Nehra",
    home: "Narendra Modi Stadium, Ahmedabad",
    titles: 1,
    titleYears: "2022",
  },
  lsg: {
    name: "Lucknow Super Giants",
    logo: "Logo/lsg.png",
    captain: "Rishabh Pant",
    coach: "Justin Langer",
    home: "BRSABV Ekana Stadium, Lucknow",
    titles: 0,
    titleYears: "Yet to Win",
  }
};
